# Generated by Django 3.2.3 on 2022-11-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSITUweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('licencia', models.CharField(max_length=10)),
                ('idplaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.bus')),
            ],
        ),
    ]
